### ISSUE TITLE
Request: Backport to 1.19.2

### ISSUE THREAD

**Issue by DemonSeedxp** [Flooflez/FreezeObservers#1]
For the shortest of moments I thought I had found the answer to all my problems I've been encountering pasting redstone builds in world edit and observers breaking everything, But then I saw it's only available in 1.20's ;( any chance  you'd consider adding 1.19.2 to your catalog? 

You'd go straight from zero to hero to me if you could wake me from this nightmare I've been living the past while. Stupid 1,734 3x3 doors that need pasted in and they just keep ripping them selves apart every time! I thought it was hopeless until I found your little miracle mod that could solve all my problems with a toggle! I so need this in my life.. Any chance that could be made to happen?

**Comment by Flooflez** [comment]
Hi there, yes this is totally something I can do.
However I’m kinda busy right now, so this might take some time. Hopefully I have sometime tomorrow to work on it.

can I ask why you’re building redstone in 1.19.2 specifically?

**Comment by DemonSeedxp** [comment]
Sure, it's mainly because several of the mods I use have not been updated just yet , but funny enough I completely by chance ran across someone in discord looking to suppress observers updates and learned from the person that responded that one of the mods I already had installed (a carpet add-on) could also do the job and I had no idea. So as luck would have it, I'm actually already covered. But nonetheless I'm still very grateful that you were so willing to help out so quickly.  So thanks anyways, but it seems you're off the hook!
